const HarvestLot = require("../models/HarvestLot");
const SampleImage = require("../models/SampleImage");
const BatchAnalysis = require("../models/BatchAnalysis");

// ==================================================
// ANALYZE HARVEST LOT
// POST /api/lots/:id/analyze
// ==================================================

const analyzeHarvestLot = async (req, res) => {
  try {
    const { id } = req.params;

    // --------------------------------------------------
    // 1. Find harvest lot
    // --------------------------------------------------

    const lot = await HarvestLot.findById(id);

    if (!lot) {
      return res.status(404).json({
        success: false,
        message: "Harvest lot not found.",
      });
    }

    // --------------------------------------------------
    // 2. Get uploaded samples
    // --------------------------------------------------

    const samples = await SampleImage.find({
      lotId: lot._id,
    }).sort({
      sampleNumber: 1,
    });

    // --------------------------------------------------
    // 3. Validate sample count
    // --------------------------------------------------

    if (samples.length < 5) {
      return res.status(400).json({
        success: false,
        message:
          "At least 5 representative samples are required.",
      });
    }

    if (samples.length > 10) {
      return res.status(400).json({
        success: false,
        message:
          "A maximum of 10 representative samples is allowed.",
      });
    }

    // --------------------------------------------------
    // 4. Mark lot as analyzing
    // --------------------------------------------------

    lot.status = "analyzing";

    await lot.save();

    // ==================================================
    // TEMPORARY DEMO QUALITY DISTRIBUTION
    //
    // IMPORTANT:
    // These values are illustrative demo values.
    // They are NOT generated by the AI model.
    //
    // Total = 100%
    // A = 68%
    // B = 23%
    // Recovery = 9%
    // ==================================================

    const gradeA = 68;
    const gradeB = 23;
    const recovery = 9;

    // --------------------------------------------------
    // 5. Calculate estimated quantities
    // --------------------------------------------------

    const totalQuantity = Number(
      lot.quantityKg
    );

    const gradeAKg = Number(
      (
        totalQuantity *
        gradeA /
        100
      ).toFixed(2)
    );

    const gradeBKg = Number(
      (
        totalQuantity *
        gradeB /
        100
      ).toFixed(2)
    );

    let recoveryKg = Number(
      (
        totalQuantity *
        recovery /
        100
      ).toFixed(2)
    );

    // --------------------------------------------------
    // 6. Correct rounding difference
    // --------------------------------------------------

    const calculatedTotal =
      gradeAKg +
      gradeBKg +
      recoveryKg;

    const roundingDifference = Number(
      (
        totalQuantity -
        calculatedTotal
      ).toFixed(2)
    );

    recoveryKg = Number(
      (
        recoveryKg +
        roundingDifference
      ).toFixed(2)
    );

    // --------------------------------------------------
    // 7. Save / update batch analysis
    // --------------------------------------------------

    const batchAnalysis =
      await BatchAnalysis.findOneAndUpdate(
        {
          lotId: lot._id,
        },
        {
          lotId: lot._id,

          samplesAnalyzed:
            samples.length,

          // Temporary demo values
          totalDetections: 0,

          averageConfidence: 0,

          qualityDistribution: {
            gradeA,
            gradeB,
            recovery,
          },

          estimatedQuantityKg: {
            gradeA: gradeAKg,
            gradeB: gradeBKg,
            recovery: recoveryKg,
          },

          assessmentMode: "demo",
        },
        {
          new: true,
          upsert: true,
        }
      );

    // --------------------------------------------------
    // 8. Mark lot as analyzed
    // --------------------------------------------------

    lot.status = "analyzed";

    await lot.save();

    // --------------------------------------------------
    // 9. Return analysis response
    // --------------------------------------------------

    return res.status(200).json({
      success: true,

      message:
        "Harvest lot analyzed successfully.",

      lot: {
        id: lot._id,
        crop: lot.crop,
        quantityKg: lot.quantityKg,
        harvestDate: lot.harvestDate,
        location: lot.location,
        status: lot.status,
      },

      batchSummary: {
        samplesAnalyzed:
          samples.length,

        totalDetections: 0,

        qualityDistribution: {
          gradeA,
          gradeB,
          recovery,
        },

        estimatedQuantityKg: {
          gradeA: gradeAKg,
          gradeB: gradeBKg,
          recovery: recoveryKg,
        },

        assessmentMode: "demo",
      },

      analysis: batchAnalysis,
    });
  } catch (error) {
    console.error(
      "Harvest analysis error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Failed to analyze harvest lot.",
      error: error.message,
    });
  }
};

// ==================================================
// GET HARVEST ANALYSIS
// GET /api/lots/:id/analysis
// ==================================================

const getHarvestAnalysis = async (req, res) => {
  try {
    const { id } = req.params;

    // --------------------------------------------------
    // 1. Find harvest lot
    // --------------------------------------------------

    const lot = await HarvestLot.findById(id);

    if (!lot) {
      return res.status(404).json({
        success: false,
        message: "Harvest lot not found.",
      });
    }

    // --------------------------------------------------
    // 2. Find saved analysis
    // --------------------------------------------------

    const analysis =
      await BatchAnalysis.findOne({
        lotId: lot._id,
      });

    if (!analysis) {
      return res.status(404).json({
        success: false,
        message:
          "No analysis found for this harvest lot.",
      });
    }

    // --------------------------------------------------
    // 3. Return analysis
    // --------------------------------------------------

    return res.status(200).json({
      success: true,

      message:
        "Harvest analysis loaded successfully.",

      data: {
        lot: {
          id: lot._id,
          crop: lot.crop,
          quantityKg: lot.quantityKg,
          harvestDate: lot.harvestDate,
          location: lot.location,
          status: lot.status,
        },

        analysis: {
          qualityDistribution:
            analysis.qualityDistribution,

          estimatedQuantityKg:
            analysis.estimatedQuantityKg,

          samplesAnalyzed:
            analysis.samplesAnalyzed,

          totalDetections:
            analysis.totalDetections,

          averageConfidence:
            analysis.averageConfidence,

          assessmentMode:
            analysis.assessmentMode,
        },
      },
    });
  } catch (error) {
    console.error(
      "Get harvest analysis error:",
      error
    );

    return res.status(500).json({
      success: false,
      message:
        "Failed to load harvest analysis.",
      error: error.message,
    });
  }
};

// ==================================================
// EXPORTS
// ==================================================

module.exports = {
  analyzeHarvestLot,
  getHarvestAnalysis,
};